# https://jekyllrb.com/docs/configuration/options/

# Server
destination: _site
keep_files:
  - assets/css
  - assets/js
host: "localhost"
baseurl: ""
exclude:
  - assets/scss
  - assets/js
  - assets/options

assets:
  compress:
    css: true
    js: true
  prefix: "/assets"
  sources:
    - "assets"
    
plugins: 
  - jekyll-assets